spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:blog-search-keyword
    username: darkship
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

api:
  kakao:
    application-key: KakaoAK 6a23baf8faae74bf04f118e9c20613c4

logging:
  level:
    com.kms.blogsearch.infrastructure.external: TRACE