spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:blog-search-keyword
    username: darkship
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
#TODO  h2:
      #    console:
      #enabled: true
      #path: /h2-console